runtime: custom
env: flex
resources:
  cpu: 1
  memory_gb: 3
service: angular-prototype
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.8
network:
  name: default
  subnetwork_name: kubernetes